pbc-front:
  build: .
  ports:
    - "80:80"
    - "443:443"
    - "9000:9000"
  links:
    - pbc-mongodb:pbc-mongodb
  build: ./
  volumes:
    - ./www:/var/www
    - ./sites:/etc/nginx/conf.d
    - ./logs:/var/log/supervisor

pbc-mongodb:
  image: mongo
  hostname: pbc-mongodb
  ports:
    - "27017:27017"
